# Generated by Django 2.0.8 on 2018-09-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFarmacia', models.CharField(max_length=50)),
                ('nomeCliente', models.CharField(max_length=50)),
                ('nomeFuncionario', models.CharField(max_length=50)),
                ('laboratorio', models.CharField(max_length=50)),
                ('nomeRemedio', models.CharField(max_length=50)),
            ],
        ),
    ]
